export const JOBS_LIST_REQUEST = 'JOBS_LIST_REQUEST'
export const JOBS_LIST_SUCCESS = 'JOBS_LIST_SUCCESS'
export const JOBS_LIST_FAIL = 'JOBS_LIST_FAIL'

export const JOB_APPLY_REQUEST = 'JOB_APPLY_REQUEST'
export const JOB_APPLY_SUCCESS = 'JOB_APPLY_SUCCESS'
export const JOB_APPLY_FAIL = 'JOB_APPLY_FAIL'